//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.01.27 at 01:36:27 PM EST 
//


package nies.ui.vocabulary;

import ghirl.graph.Graph;
import ghirl.graph.PathSearcher;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlTransient;
import javax.xml.bind.annotation.XmlType;

import org.apache.log4j.Logger;


/**
 * <p>Java class for LabelDescription complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LabelDescription">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}selector"/>
 *         &lt;element name="style" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="default" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="defaultStyle" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.NONE)
@XmlType(name = "LabelDescription", propOrder = {
    "selectorPath",
    "style",
    "default",
    "defaultStyle"
})
public class LabelDescription {
	private static final Logger logger = Logger.getLogger(LabelDescription.class);
	protected Graph graph;
	protected PathSearcher selector;
    private String selectorPath;
    protected String style;
    protected String _default;
    protected String defaultStyle;

    public LabelDescription() {}
    public LabelDescription(Graph g) { this.graph = g; }
    
    public void setGraph(Graph g) { this.graph = g; }
    
    public PathSearcher getSelector() {
    	if (selector == null) logger.error("Label selector was never set! selectorPath is "+selectorPath);
    	if (selector.getGraph() == null) {
    		if (this.graph == null) {
    			 logger.warn("Selector is invalid -- LabelDescription has not been provided with a Graph!");
    		} else {
    			selector.setGraph(graph);
    		}
    	}
        return selector;
    }


    @XmlElement(required = true)
    public String getSelectorPath() { return selectorPath; }
    /**
     * Sets the value of the selector property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSelectorPath(String value) {
    	selectorPath = value;
        setSelector(new PathSearcher(value));
    }
    
    public void setSelector(PathSearcher sel) {
    	this.selector=sel;
        if (this.graph != null) 
        	selector.setGraph(graph);
    }

    /**
     * Gets the value of the style property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @XmlElement
    public String getStyle() {
        return style;
    }

    /**
     * Sets the value of the style property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStyle(String value) {
        this.style = value;
    }


    /**
     * Gets the value of the default property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @XmlElement(defaultValue = "(none)")
    public String getDefault() {
        return _default;
    }

    /**
     * Sets the value of the default property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDefault(String value) {
        this._default = value;
    }

    /**
     * Gets the value of the defaultStyle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @XmlElement
    public String getDefaultStyle() {
        return defaultStyle;
    }

    /**
     * Sets the value of the defaultStyle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDefaultStyle(String value) {
        this.defaultStyle = value;
    }

}
