//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.01.27 at 01:36:27 PM EST 
//


package nies.ui.vocabulary;

import ghirl.graph.Graph;
import ghirl.graph.GraphId;
import ghirl.graph.NodeFilter;
import ghirl.graph.PathSearcher;
import ghirl.util.Distribution;

import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import nies.ui.vocabulary.AttributeAssertion;
import nies.ui.vocabulary.ResourceResult;
import nies.ui.vocabulary.TypeDescription;
import nies.ui.vocabulary.TypeResult;

import org.apache.log4j.Logger;


/**
 * <p>Java class for TypeDescription complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TypeDescription">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="title" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element ref="{}selector" minOccurs="0"/>
 *         &lt;element ref="{}filter" minOccurs="0"/>
 *         &lt;element name="label" type="{}LabelDescription" minOccurs="0"/>
 *         &lt;element name="max" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="more" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="attributes" type="{}AttributesList" minOccurs="0"/>
 *         &lt;element name="assertAttributes" type="{}AssertAttributesList" minOccurs="0"/>
 *         &lt;element name="resourceDelimiter" type="{}Delimiter" minOccurs="0"/>
 *         &lt;element name="attributeDelimiter" type="{}Delimiter" minOccurs="0"/>
 *         &lt;element name="typeclass" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="titleclass" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="resourceclass" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="labelclass" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.NONE)
@XmlType(name = "TypeDescription", propOrder = {
    "title",
    "selectorPath",
    "filterString",
    "label",
    "max",
    "more",
    "attributes",
    "assertAttributes",
    "resourceDelimiter",
    "attributeDelimiter",
    "typeclass",
    "titleclass",
    "resourceclass",
    "labelclass"
})
public class TypeDescription extends Transformer {
	private static final Logger logger = Logger.getLogger(TypeDescription.class);
	
    protected String title;
    protected LabelDescription label;
    protected Integer max;
    protected Boolean more;
    protected AttributesList attributes;
    protected AssertAttributesList assertAttributes;
    protected Delimiter resourceDelimiter;
    protected Delimiter attributeDelimiter;
    protected String typeclass;
    protected String titleclass;
    protected String resourceclass;
    protected String labelclass;
    protected String name;

    /** Empty constructor for JAXB use only. */
    public TypeDescription() {
		this.resourceDelimiter = Delimiter.BLOCK;
		this.attributeDelimiter = Delimiter.BLOCK;
		this.typeclass = "type";
		this.titleclass = "title";
		this.resourceclass = "resource";
		this.labelclass = "label";
    }
	public TypeDescription(String name, Graph g) {
		this(); // set defaults
		this.name = name;
		this.graph = g;
	}
	
	public TypeResult compile(Distribution nodeset) {
		TypeResult t = new TypeResult(this);
		
		int s = nodeset.size();
		if (s==1) logger.debug("Compiling type "+this.name+" for node "+((GraphId)nodeset.iterator().next()).getShortName());
		else logger.debug("Compiling type "+this.name+" for "+s+" nodes. ");
		GraphId i;
		for(Iterator it = nodeset.iterator(); it.hasNext(); ) { i=(GraphId) it.next();
			t.addResource(this.compile(i));
		}
		return t;
	}
	public ResourceResult compile(GraphId node) {
		ResourceResult r = new ResourceResult(this);
		
		// set the label
		if (label != null) {
			Distribution d = label.getSelector().search(node);
			if (d.size() < 1) {
				r.setLabel(label.getDefault());
			} else {
				GraphId i = (GraphId) d.iterator().next();
				String s = graph.getTextContent(i); 
				if (s.equals("")) r.setLabel(i.getShortName());
				else r.setLabel(s);
			}
		}
		
		// set the attributes
		if (attributes != null) {
			for (Attribute att : attributes.getAttribute()) {
				TypeDescription td = att.getType();
				r.addAttribute(td.compile(td.transform(node)));
			}
		}
		
		return r;
	}
	
	public boolean meetsAssertions(GraphId node) {
		for(AttributeAssertion asst : assertAttributes.getAttributeAssertion()) {
			if (!asst.accepts(node)) return false;
		}
		return true;
	}
    
	public Graph getGraph() { return graph; }
    /**
     * Set the graph used by the selectors in this TypeDescription tree.  Automatically 
     * recurses to all child (attribute) TypeDescription objects and labels.
     * @param g The graph to set.
     */
	public void setGraph(Graph g) {
		this.graph = g;
		this.label.setGraph(g);
		if (this.attributes == null) return;
		for (Attribute at : this.attributes()) {
			at.getType().setGraph(g);
		}
	}
	
    /* ***** Auto-generated code ***** */
    
    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
	@XmlElement
    public String getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitle(String value) {
        this.title = value;
    }

	@XmlElement
    public String getSelectorPath() { return null; }
    /**
     * Sets the value of the selector property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSelectorPath(String value) {
        this.selector = new PathSearcher(value);
    }

	@XmlElement
    public String getFilterString() { return null; }
    /**
     * Sets the value of the filter property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFilterString(String value) {
        this.filter = new NodeFilter(value);
    }

    /**
     * Gets the value of the label property.
     * 
     * @return
     *     possible object is
     *     {@link LabelDescription }
     *     
     */
	@XmlElement
    public LabelDescription getLabel() {
        return label;
    }

    /**
     * Sets the value of the label property.
     * 
     * @param value
     *     allowed object is
     *     {@link LabelDescription }
     *     
     */
    public void setLabel(LabelDescription value) {
        this.label = value;
    }

    /**
     * Gets the value of the max property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
	@XmlElement
    public Integer getMax() {
        return max;
    }

    /**
     * Sets the value of the max property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMax(Integer value) {
        this.max = value;
    }

    /**
     * Gets the value of the more property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    @XmlElement(defaultValue = "true")
    public Boolean isMore() {
        return more;
    }

    /**
     * Sets the value of the more property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setMore(Boolean value) {
        this.more = value;
    }

    /**
     * Gets the value of the attributes property.
     * 
     * @return
     *     possible object is
     *     {@link AttributesList }
     *     
     */
	@XmlElement
    public AttributesList getAttributes() {
        return attributes;
    }
	
	public List<Attribute> attributes() {
		if (attributes == null) return null;
		return attributes.getAttribute();
	}

    /**
     * Sets the value of the attributes property.
     * 
     * @param value
     *     allowed object is
     *     {@link AttributesList }
     *     
     */
    public void setAttributes(AttributesList value) {
        this.attributes = value;
    }
    
    public void addAttribute(TypeDescription td) {
    	this.attributes.getAttribute().add(new Attribute(td.getName()));
    	Configuration.set(td.getName(), td);
    }

    /**
     * Gets the value of the assertAttributes property.
     * 
     * @return
     *     possible object is
     *     {@link AssertAttributesList }
     *     
     */
    public List<AttributeAssertion> assertAttributes() {
        return assertAttributes.getAttributeAssertion();
    }
    

	@XmlElement
	public AssertAttributesList getAssertAttributes() {
		return assertAttributes;
	}

    /**
     * Sets the value of the assertAttributes property.
     * 
     * @param value
     *     allowed object is
     *     {@link AssertAttributesList }
     *     
     */
    public void setAssertAttributes(AssertAttributesList value) {
        this.assertAttributes = value;
    }

    /**
     * Gets the value of the resourceDelimiter property.
     * 
     * @return
     *     possible object is
     *     {@link Delimiter }
     *     
     */
    @XmlElement(defaultValue = "block")
    public Delimiter getResourceDelimiter() {
        return resourceDelimiter;
    }

    /**
     * Sets the value of the resourceDelimiter property.
     * 
     * @param value
     *     allowed object is
     *     {@link Delimiter }
     *     
     */
    public void setResourceDelimiter(Delimiter value) {
        this.resourceDelimiter = value;
    }

    /**
     * Gets the value of the attributeDelimiter property.
     * 
     * @return
     *     possible object is
     *     {@link Delimiter }
     *     
     */
    @XmlElement(defaultValue = "block")
    public Delimiter getAttributeDelimiter() {
        return attributeDelimiter;
    }

    /**
     * Sets the value of the attributeDelimiter property.
     * 
     * @param value
     *     allowed object is
     *     {@link Delimiter }
     *     
     */
    public void setAttributeDelimiter(Delimiter value) {
        this.attributeDelimiter = value;
    }

    /**
     * Gets the value of the typeclass property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @XmlElement(defaultValue = "type")
    public String getTypeclass() {
        return typeclass;
    }

    /**
     * Sets the value of the typeclass property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTypeclass(String value) {
        this.typeclass = value;
    }

    /**
     * Gets the value of the titleclass property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @XmlElement(defaultValue = "title")
    public String getTitleclass() {
        return titleclass;
    }

    /**
     * Sets the value of the titleclass property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitleclass(String value) {
        this.titleclass = value;
    }

    /**
     * Gets the value of the resourceclass property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @XmlElement(defaultValue = "resource")
    public String getResourceclass() {
        return resourceclass;
    }

    /**
     * Sets the value of the resourceclass property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResourceclass(String value) {
        this.resourceclass = value;
    }

    /**
     * Gets the value of the labelclass property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @XmlElement(defaultValue = "label")
    public String getLabelclass() {
        return labelclass;
    }

    /**
     * Sets the value of the labelclass property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLabelclass(String value) {
        this.labelclass = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @XmlAttribute(required = true)
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

}
